[versions]

kotlin = "1.6.10"
clikt = "3.4.0"

[libraries]

clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }

[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
